apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sogo.fullname" . }}-configuration
  labels:
    {{- include "sogo.labels" . | nindent 4 }}
data:
  sogo.conf: {{ tpl (.Files.Get "conf/sogo.conf") . | quote }}
