name: Release helm chart

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release helm chart
    runs-on: ubuntu:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Configure git
        run: |
          git config user-name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      
      - name: Install helm
        uses: azure/setup-helm@v1
        with:
          version: v1.4.0
      
      - name: Run chart release
        uses: helm/chart-releaser-action@v1.2.1
        with:
          chart_dir: helm
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
